name: Create Docker Image + E2E Tests

on:
  push:
    tags:
    - '**'
    branches:
    - '**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      branchTag: ${{ steps.meta.outputs.version }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build
        uses: strangelove-ventures/heighliner-build-action@v0.0.2
        with:
          chain: noble
          dockerfile: cosmos
          build-target: make install
          binaries: |
            - /go/bin/nobled

  test-tkn-factory:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go
              
      - name: checkout chain
        uses: actions/checkout@v2
        
      - run: make ictest-tkn-factory
        env:
          BRANCH_CI: ${{needs.build-and-push-image.outputs.branchTag}}

  test-packet-forward:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go
              
      - name: checkout chain
        uses: actions/checkout@v2
        
      - run: make ictest-packet-forward
        env:
          BRANCH_CI: ${{needs.build-and-push-image.outputs.branchTag}}

  test-param-authority:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go
              
      - name: checkout chain
        uses: actions/checkout@v2
        
      - run: make ictest-paramauthority
        env:
          BRANCH_CI: ${{needs.build-and-push-image.outputs.branchTag}}

  test-chain-upgrade-authority:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go
              
      - name: checkout chain
        uses: actions/checkout@v2
        
      - run: make ictest-chain-upgrade
        env:
          BRANCH_CI: ${{needs.build-and-push-image.outputs.branchTag}}

  test-globalfee-module:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go
              
      - name: checkout chain
        uses: actions/checkout@v2
        
      - run: make ictest-globalFee
        env:
          BRANCH_CI: ${{needs.build-and-push-image.outputs.branchTag}}

  test-ics20-bps-fees:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go
              
      - name: checkout chain
        uses: actions/checkout@v2
        
      - run: make ictest-ics20-bps-fees
        env:
          BRANCH_CI: ${{needs.build-and-push-image.outputs.branchTag}}
